name: "CI: Biblus"

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches:
    - master
    - main
    paths-ignore: ["docs/**"]

  push:
    branches:
    - master
    - main
    paths-ignore: ["docs/**"]

  workflow_dispatch:

concurrency:
  group: "build"
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            requirements/base.txt

      - name: pre-commit
        run: |
          python3.11 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements/base.txt
          pre-commit run --show-diff-on-failure --color=always --all-files

  builder-biblus:
    environment: production
    runs-on: ubuntu-latest
    needs:
      - linter
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: "./compose/Dockerfile"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/biblus:latest

  testing:
    environment: production
    runs-on: ubuntu-latest
    needs:
      - builder-biblus
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            requirements/production.txt

      - name: Install dependencies
        run: |
          python3.11 -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements/production.txt

      - name: Test with pytest
        run: |
          python3.11 -m venv .venv
          source .venv/bin/activate
          pip install pytest pytest-cov pytest-asyncio
          pytest src/tests/tests.py -W ignore::DeprecationWarning --doctest-modules --junitxml=junit/test-results.xml --cov=src/tests/ --cov-report=xml --cov-report=html
